spring.application.name=DAY02
payment.provider=razor


#to check which been is used
#you can also creaet payment provider click on 3dots click edit configuration in environment variables add in upper case instaed of dots give (.=>_)
#like payment.provider=razor for this PAYMENT_PROVIDER=phonepe
#debug=true